#!/usr/bin/env python3
"""Export runtime-harvested indirect-dispatch knowledge to the DKC1 IDA DB.

The recomp cfgs carry every proven indirect-dispatch contract (site, kind,
and the exact runtime-harvested target set — e.g. the $BE8179 anim-callback
with its 15 targets). Static analysis cannot see these edges, so private
renderers and special level logic reached only through them look like dead
code in the database.

This tool parses `recomp/bank*.cfg`, writes an IDAPython annotation script
(user-code xrefs site->target, repeatable comments with provenance, and
function creation at unexplored targets), and optionally applies it to the
seeded database headlessly.

usage:
  python tools/export_ida_dispatch.py                # generate script only
  python tools/export_ida_dispatch.py --apply        # also run idat -A
"""
from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_DATABASE = Path(
    r"D:\Downloads\DKLR\DKC1_Disassembly\Tools\IDA\DKC1_U1.i64")
DEFAULT_IDAT = Path(
    r"C:\Program Files\IDA Professional 9.3\idat.exe")

LINE = re.compile(
    r"^indirect_dispatch\s+([0-9A-Fa-f]{4})\s+(\d+)\s+(\S+)"
    r"(.*?)targets:([0-9A-Fa-f,]+)", re.M)


def collect() -> list[dict]:
    dispatches = []
    for cfg in sorted((REPO / "recomp").glob("bank*.cfg")):
        bank = int(cfg.stem.replace("bank", ""), 16)
        for match in LINE.finditer(cfg.read_text()):
            addr16, count, kind, attrs, targets = match.groups()
            dispatches.append({
                "site": (bank << 16) | int(addr16, 16),
                "kind": kind,
                "attrs": attrs.strip(),
                "targets": [int(t, 16) for t in targets.split(",")],
                "cfg": cfg.name,
            })
    return dispatches


def emit_script(dispatches: list[dict], out: Path) -> None:
    lines = [
        "# Auto-generated by DKC1Recomp tools/export_ida_dispatch.py.",
        "# Adds runtime-proven dispatch edges to the seeded database:",
        "# user-code xrefs site->target, provenance comments, functions at",
        "# unexplored targets. Idempotent; safe to re-apply.",
        "import ida_auto",
        "import ida_bytes",
        "import ida_funcs",
        "import ida_kernwin",
        "import ida_xref",
        "import idc",
        "",
        "DISPATCHES = [",
    ]
    for d in dispatches:
        lines.append(f"    (0x{d['site']:06X}, {d['kind']!r}, "
                     f"{d['attrs']!r}, {d['cfg']!r}, [")
        for t in d["targets"]:
            lines.append(f"        0x{t:06X},")
        lines.append("    ]),")
    lines += [
        "]",
        "",
        "def apply():",
        "    added_xrefs = added_funcs = skipped = 0",
        "    for site, kind, attrs, cfg, targets in DISPATCHES:",
        "        if not ida_bytes.is_loaded(site):",
        "            skipped += 1",
        "            continue",
        "        comment = ('runtime dispatch (%s%s): %d targets proven by '",
        "                   'DKC1Recomp trace harvest [%s]' % (",
        "                       kind, (' ' + attrs) if attrs else '',",
        "                       len(targets), cfg))",
        "        idc.set_cmt(site, comment, 1)",
        "        for target in targets:",
        "            if not ida_bytes.is_loaded(target):",
        "                skipped += 1",
        "                continue",
        "            if ida_xref.add_cref(site, target,",
        "                                 ida_xref.fl_CN | ida_xref.XREF_USER):",
        "                added_xrefs += 1",
        "            if ida_funcs.get_func(target) is None:",
        "                if ida_funcs.add_func(target):",
        "                    added_funcs += 1",
        "            name = idc.get_name(target) or ''",
        "            if not name or name.startswith(('unk_', 'loc_',",
        "                                            'byte_', 'word_')):",
        "                idc.set_name(target,",
        "                             'DispatchTarget_%06X' % target,",
        "                             idc.SN_NOWARN | idc.SN_NOCHECK)",
        "    print('dispatch import: %d xrefs, %d new funcs, %d skipped'",
        "          % (added_xrefs, added_funcs, skipped))",
        "",
        "apply()",
        "ida_auto.auto_wait()",
        "# headless runs exit; interactive runs leave the DB open",
        "if ida_kernwin.cvar.batch:",
        "    idc.qexit(0)",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path,
                        default=REPO / "build/ida_dispatch_annotations.py")
    parser.add_argument("--database", type=Path, default=DEFAULT_DATABASE)
    parser.add_argument("--idat", type=Path, default=DEFAULT_IDAT)
    parser.add_argument("--apply", action="store_true",
                        help="run idat headlessly to apply the annotations")
    args = parser.parse_args()

    dispatches = collect()
    total_targets = sum(len(d["targets"]) for d in dispatches)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    emit_script(dispatches, args.out)
    print(f"{len(dispatches)} dispatch sites, {total_targets} targets "
          f"-> {args.out}")
    if not args.apply:
        print("apply with --apply, or in IDA: File > Script file...")
        return 0
    if not args.database.exists() or not args.idat.exists():
        print("error: database or idat.exe not found; adjust --database/"
              "--idat")
        return 2
    result = subprocess.run(
        [str(args.idat), "-A", f"-S{args.out.resolve()}",
         str(args.database)],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print(result.stdout[-1500:] if result.stdout else "(no output)")
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
