#!/usr/bin/env python3
"""Verify and stage routine replacements (DKC1_REPLACE build step).

Reads runner/replacements/manifest.json and, for each declared
replacement, FAILS CLOSED unless every check passes:
  - the ROM is the supported one (sha256);
  - the replaced region's actual ROM bytes (entry..end from the recomp
    cfg facts, HiROM mirror fold) hash to the manifest's blessed
    region_sha256 (--bless records it from the supported ROM);
  - the declared M/X mode matches the proven entry facts;
  - exactly one generated TU defines the variant symbol.

On success emits build/replacements/overrides.bat: recompiles the
defining TU with the variant renamed to <variant>_original and compiles
the replacement sources, so the replacement takes over every call site
(direct and dispatch) at link time while the original remains callable
as the runtime fallback.

usage: python tools/gen_replacements.py --rom R [--bless]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

from ir import decode  # noqa: E402

REPO = TOOLS.parent
MANIFEST = REPO / "runner" / "replacements" / "manifest.json"
OUT_DIR = REPO / "build" / "replacements"
SUPPORTED_ROM_SHA = ("fa8cacf5bbfc39ee6bbaa557adf89133d60d42f6"
                     "cf9e1db30d5a36a469f74d15")
MODE_OF_MX = {(0, 0): "M16X16", (0, 1): "M16X8",
              (1, 0): "M8X16", (1, 1): "M8X8"}


def fail(message: str) -> None:
    sys.exit(f"replacement staging REFUSED: {message}")


def region_bytes(rom: bytes, start: int, end: int) -> bytes:
    out = bytearray()
    for pc24 in range(start, end):
        offset = decode.rom_offset(pc24)
        if offset is None or offset >= len(rom):
            fail(f"unmappable pc 0x{pc24:06X} in region")
        out.append(rom[offset])
    return bytes(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rom", required=True, type=Path)
    parser.add_argument("--bless", action="store_true",
                        help="record region hashes from the supported ROM")
    args = parser.parse_args()

    rom = args.rom.read_bytes()
    if len(rom) % 0x8000 == 0x200:
        rom = rom[0x200:]
    if hashlib.sha256(rom).hexdigest() != SUPPORTED_ROM_SHA:
        fail(f"{args.rom} is not the supported ROM")

    manifest = json.loads(MANIFEST.read_text())
    facts = decode.load_func_facts()
    lines = ["rem GENERATED by tools/gen_replacements.py - do not edit.",
             "rem Recompiles defining TUs with the variant renamed to",
             "rem *_original, then compiles the replacement sources."]
    for entry in manifest["replacements"]:
        label = entry["label"]
        variant = entry["variant"]
        addr = int(label.replace("CODE_", ""), 16)
        fact = facts.get(addr)
        if fact is None:
            fail(f"{label}: no recomp func fact")
        mode = MODE_OF_MX.get(fact["entry_mx"])
        if mode != entry.get("mode"):
            fail(f"{label}: manifest mode {entry.get('mode')} != proven "
                 f"{mode}")
        digest = hashlib.sha256(
            region_bytes(rom, addr, fact["end"])).hexdigest()
        if args.bless:
            entry["region_sha256"] = digest
            print(f"{label}: blessed region 0x{addr:06X}..0x{fact['end']:06X} "
                  f"sha256 {digest[:16]}...")
        elif entry.get("region_sha256") != digest:
            fail(f"{label}: region bytes changed (manifest "
                 f"{str(entry.get('region_sha256'))[:16]}... vs ROM "
                 f"{digest[:16]}...) — re-verify and --bless deliberately")

        needle = f"RecompReturn {variant}(CpuState *cpu) {{"
        defining = [p for p in sorted(
            (REPO / "generated" / "snesrecomp").glob("*.c"))
            if needle in p.read_text(encoding="utf-8", errors="replace")]
        if len(defining) != 1:
            fail(f"{label}: {len(defining)} TUs define {variant} "
                 f"(need exactly 1): {[p.name for p in defining]}")
        lines.append(
            f"cl /nologo /c /W0 /O1 %DEFS% %INCS% "
            f"/D{variant}={variant}_original "
            f"..\\..\\generated\\snesrecomp\\{defining[0].name}")
        lines.append("if errorlevel 1 exit /b 1")
        print(f"{label}: {variant} in {defining[0].name}, mode {mode}, "
              "region verified")

    lines.append("cl /nologo /c /W0 /O1 %DEFS% %INCS% "
                 "..\\..\\runner\\replacements\\dkc1_replacements.c")
    lines.append("if errorlevel 1 exit /b 1")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "overrides.bat").write_text("\r\n".join(lines) + "\r\n")
    if args.bless:
        MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"staged {len(manifest['replacements'])} replacement(s) -> "
          f"{OUT_DIR / 'overrides.bat'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
