#!/usr/bin/env python3
"""Generate runner/dkc1_wram_gen.h — typed views over authentic WRAM.

Emits, from the disassembly's own RAM map + struct declarations + the
curated rename_map:
  - named offset macros for every RAM-map label (curated name when one
    exists, label otherwise; both spellings kept in the comment)
  - little-endian u8/u16 view accessors (reads/writes go straight to
    the live WRAM buffer — views, never duplicated state; u16 stores
    wrap exactly like the hardware by taking uint16_t)
  - per-field actor SoA accessors (slot = the raw even byte index
    $02..$32 the game itself keeps in X/Y)
  - struct mirrors (OAM buffer etc.) with base/stride/field offsets

Verification (--check):
  - regenerates and diffs against the file on disk (staleness gate)
  - cross-validates every emitted address against tools/atlas.py's
    INDEPENDENT RAM-map parser — two parsers must agree byte-for-byte

usage: python tools/gen_wram_header.py [--check]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

import atlas  # noqa: E402
from ir import memtype  # noqa: E402

REPO = TOOLS.parent
OUT = REPO / "runner" / "dkc1_wram_gen.h"


def c_ident(name: str) -> str:
    name = re.sub(r"^RAM_DKC1_", "", name)
    name = re.sub(r"^DKC1_", "", name)   # emitted macros add their own
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if name and name[0].isdigit():
        name = "_" + name
    return name


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()

    resolver = memtype.Resolver()
    _, ram_names = atlas.load_rename_map()
    ram_labels = atlas.load_ram_map_labels()   # independent parser

    # named offsets: every RAM-map label, curated overlay when present
    entries = []       # (ident, addr, label, curated)
    used: dict[str, int] = {}
    for addr in sorted(ram_labels):
        for label in ram_labels[addr]:
            resolved = resolver.defines.get(label)
            if resolved is None or (resolved & 0x1FFFF) != addr:
                print(f"CROSS-PARSER MISMATCH: {label} atlas=0x{addr:X} "
                      f"memtype={resolved}")
                return 1
            curated = ram_names.get(addr)
            name = curated["name"] if curated and curated.get("name") \
                else None
            ident = c_ident(name or label)
            if ident in used and used[ident] != addr:
                ident = f"{ident}_{addr:04X}"
            used[ident] = addr
            entries.append((ident, addr, label, name))

    lines = [
        "/* dkc1_wram_gen.h — GENERATED by tools/gen_wram_header.py.",
        " * DO NOT EDIT. Regenerate after RAM-map/rename updates:",
        " *   python tools/gen_wram_header.py",
        " * Views over authentic WRAM (offset = address & 0x1FFFF);",
        " * little-endian, exact 16-bit wrap. Never duplicated state. */",
        "#ifndef DKC1_WRAM_GEN_H",
        "#define DKC1_WRAM_GEN_H",
        "",
        "#include <stdint.h>",
        "",
        "static inline uint8_t Dkc1WramU8(const uint8_t *wram,",
        "                                 uint32_t off) {",
        "  return wram[off];",
        "}",
        "static inline uint16_t Dkc1WramU16(const uint8_t *wram,",
        "                                   uint32_t off) {",
        "  return (uint16_t)(wram[off] | ((uint16_t)wram[off + 1] << 8));",
        "}",
        "static inline void Dkc1WramSetU8(uint8_t *wram, uint32_t off,",
        "                                 uint8_t value) {",
        "  wram[off] = value;",
        "}",
        "static inline void Dkc1WramSetU16(uint8_t *wram, uint32_t off,",
        "                                  uint16_t value) {",
        "  wram[off] = (uint8_t)value;",
        "  wram[off + 1] = (uint8_t)(value >> 8);",
        "}",
        "",
        "/* actor SoA slot: the raw even byte index the game keeps in",
        " * X/Y ($02..$32); pass it through unchanged. */",
        "#define DKC1_ACTOR_SLOT_FIRST 0x02u",
        "#define DKC1_ACTOR_SLOT_LAST 0x32u",
        "#define DKC1_ACTOR_SLOT_STEP 0x04u",
        "",
        "/* --- named WRAM offsets (RAM map + curated overlay) --- */",
    ]
    for ident, addr, label, name in entries:
        source = f"!{label}" + (f" (curated: {name})" if name else "")
        lines.append(f"#define DKC1_WRAM_{ident} 0x{addr:04X}u"
                     f"  /* {source} */")

    lines += ["", "/* --- actor SoA per-field accessors --- */"]
    for ident, addr, label, name in entries:
        soa = re.fullmatch(r"RAM_DKC1_NorSpr_(\w+)", label)
        if not soa:
            continue
        field = c_ident(name or soa.group(1))
        lines += [
            f"static inline uint16_t Dkc1Actor_{field}("
            f"const uint8_t *wram, uint32_t slot) {{",
            f"  return Dkc1WramU16(wram, 0x{addr:04X}u + slot);",
            "}",
            f"static inline void Dkc1Actor_Set{field}("
            f"uint8_t *wram, uint32_t slot, uint16_t value) {{",
            f"  Dkc1WramSetU16(wram, 0x{addr:04X}u + slot, value);",
            "}",
        ]

    lines += ["", "/* --- struct mirrors (Asar struct declarations) --- */"]
    for struct_name in sorted(resolver.structs):
        struct = resolver.structs[struct_name]
        if not isinstance(struct, dict):
            continue
        base = struct["base"] & 0x1FFFF
        if struct["base"] >= 0x2000 and struct["base"] < 0x8000:
            continue  # MMIO structs (HDMA regs) are not WRAM views
        ident = c_ident(struct_name)
        lines.append(f"#define DKC1_{ident}_BASE 0x{base:04X}u")
        lines.append(f"#define DKC1_{ident}_STRIDE "
                     f"0x{struct['stride']:02X}u")
        for field, offset in struct["fields"].items():
            lines += [
                f"static inline uint8_t Dkc1_{ident}_{field}("
                f"const uint8_t *wram, uint32_t index) {{",
                f"  return Dkc1WramU8(wram, 0x{base:04X}u + index * "
                f"0x{struct['stride']:02X}u + 0x{offset:02X}u);",
                "}",
            ]

    lines += ["", "#endif /* DKC1_WRAM_GEN_H */", ""]
    text = "\n".join(lines)

    if args.check:
        current = args.out.read_text() if args.out.exists() else ""
        if current != text:
            print(f"STALE: {args.out} differs from regenerated content")
            return 1
        print(f"ok: {args.out} current ({len(entries)} offsets, "
              "cross-parser agreement)")
        return 0

    args.out.write_text(text)
    soa_count = sum(1 for _, _, label, _ in entries
                    if label.startswith("RAM_DKC1_NorSpr_"))
    print(f"{args.out}: {len(entries)} named offsets, {soa_count} actor "
          f"SoA fields, {len(resolver.structs)} structs "
          "(cross-parser agreement verified)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
