#!/usr/bin/env python3
"""Generate snesrecomp per-bank CFG files for DKC1 (USA v1.0).

Structural facts come from the Yoshifanatic1 DKC1 disassembly (GPL-3), as
distilled by the IDA pipeline in the disassembly repo (`Tools/IDA/`):

* ``exact_code.json``   — start/size of every instruction, derived from the
  asar WLA symbol map's addr-to-line section (byte-exact, no heuristics);
* ``functions.json``    — function entries (call targets + named routines)
  with the semantic names applied during the 2026-08-15 analysis pass;
* ``funcs_mx.json``     — proven entry M/X flag state per function;
* ``recomp_seed/indirect_dispatch.txt`` — every ``JMP/JSR (abs,X)`` site with
  target lists extracted from the disassembly's own ``dw`` jump tables.

The output contains only names, PCs, and structural CFG metadata — no ROM
bytes and no assembly source. DKC1 executes all code from banks 80-BF (the
low-RAM-mirror halves of the HiROM space); cfg banks follow that layout.
"""
from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

BANNER = ("# Auto-generated by tools/ingest_dkc1_disasm.py.\n"
          "# Source: Yoshifanatic1 byte-exact DKC1 disassembly (GPL-3) via "
          "Tools/IDA pipeline.\n")

SITE_RE = re.compile(
    r"^([0-9A-F]{2}):([0-9A-F]{4})\s+(\S+)\s+table=(\S+)\s+count=(\d+)\s+targets:(\S+)$")


def sanitize(name: str, used: set[str]) -> str:
    clean = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not clean or clean[0].isdigit():
        clean = "f_" + clean
    base, n = clean, 2
    while clean in used:
        clean = f"{base}_{n}"
        n += 1
    used.add(clean)
    return clean


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--work", required=True, type=Path,
                        help="disassembly repo Tools/IDA/work directory")
    parser.add_argument("--out", required=True, type=Path,
                        help="output cfg directory (recomp/)")
    args = parser.parse_args()

    work: Path = args.work
    out: Path = args.out
    out.mkdir(parents=True, exist_ok=True)

    items = json.load((work / "exact_code.json").open())
    items.sort(key=lambda t: t[0])
    funcs = json.load((work / "functions.json").open())
    mx = json.load((work / "funcs_mx.json").open())
    banks = sorted(int(l, 16) for l in (work / "mirror_banks.txt").read_text().split())
    bank_set = set(banks)

    # label map (for naming dispatch targets that are not yet functions)
    addr_label: dict[int, str] = {}
    in_labels = False
    for line in (work / "DKC1_U1.sym").open(encoding="utf-8", errors="replace"):
        line = line.strip()
        if line.startswith("["):
            in_labels = line.lower() == "[labels]"
            continue
        m = re.match(r"^([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(\S+)$", line) if in_labels else None
        if m:
            ea = (int(m.group(1), 16) << 16) | int(m.group(2), 16)
            addr_label.setdefault(ea, m.group(3))

    # contiguous code runs per bank
    runs_by_bank: dict[int, list[list[int]]] = defaultdict(list)
    for ea, size, _sr, _sv in items:
        bank = ea >> 16
        runs = runs_by_bank[bank]
        if runs and runs[-1][0] + runs[-1][1] == ea:
            runs[-1][1] += size
        else:
            runs.append([ea, size])

    # function entries per bank (functions.json + dispatch targets)
    entries: dict[int, dict[int, dict]] = defaultdict(dict)  # bank -> pc16 -> rec
    used_names: set[str] = set()
    for f in sorted(funcs, key=lambda f: int(f["ea"], 16)):
        ea = int(f["ea"], 16)
        bank = ea >> 16
        if bank not in bank_set:
            continue
        m_flag, x_flag = mx.get("%X" % ea, [-1, -1])
        entries[bank][ea & 0xFFFF] = {
            "name": sanitize(f["name"], used_names),
            "mx": (m_flag if m_flag in (0, 1) else 0, x_flag if x_flag in (0, 1) else 0),
        }

    # indirect dispatch sites
    dispatch: dict[int, list[str]] = defaultdict(list)
    unresolved: dict[int, list[str]] = defaultdict(list)
    n_sites = n_targets = 0
    seed = work / "recomp_seed" / "indirect_dispatch.txt"
    for line in seed.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        if "UNRESOLVED" in line:
            b = int(line[:2], 16)
            unresolved[b].append("# TODO(dispatch): " + line)
            continue
        m = SITE_RE.match(line)
        if not m:
            continue
        bank, pc16 = int(m.group(1), 16), int(m.group(2), 16)
        opname = m.group(3)
        mode = "ptrcall" if opname.startswith("JSR") else "ptrtail"
        targets: list[str] = []
        seen: set[str] = set()
        ok = True
        for t in m.group(6).split(","):
            tm = re.match(r"^([0-9A-F]{2}):([0-9A-F]{4})$", t)
            if not tm:
                ok = False  # unresolved symbol inside the table
                break
            v = tm.group(1) + tm.group(2)
            if v not in seen:
                seen.add(v)
                targets.append(v)
        if not ok or not targets:
            unresolved[bank].append("# TODO(dispatch): " + line[:120])
            continue
        dispatch[bank].append(
            f"indirect_dispatch {pc16:04X} {len(targets)} {mode} targets:{','.join(targets)}")
        n_sites += 1
        n_targets += len(targets)
        # every dispatch target becomes an analysis entry too
        for v in targets:
            tea = int(v, 16)
            tbank, tpc = tea >> 16, tea & 0xFFFF
            if tbank in bank_set and tpc not in entries[tbank]:
                label = addr_label.get(tea, "INDIRECT_%06X" % tea)
                entries[tbank][tpc] = {"name": sanitize(label, used_names), "mx": (0, 0)}

    # write bank00 bootstrap
    (out / "bank00.cfg").write_text(
        "# DKC1 architectural bootstrap; generated by ingest_dkc1_disasm.py.\n"
        "bank = 0\nauto_vectors\ntier_down_stubs\n", newline="\n")

    total_funcs = total_regions = 0
    for bank in banks:
        runs = runs_by_bank.get(bank, [])
        ents = entries.get(bank, {})
        if not runs and not ents:
            continue
        lines = [f"bank = 0x{bank:02X}", "", BANNER.rstrip(), ""]

        # interior data regions: gaps between code runs
        regions = []
        for (a, alen), (b, _blen) in zip(runs, runs[1:]):
            gap_start, gap_end = a + alen, b
            if gap_end > gap_start:
                regions.append((gap_start & 0xFFFF, gap_end & 0xFFFF))
        lines.append(f"# {len(ents)} entries, {len(regions)} interior data regions.")
        for s, e in regions:
            lines.append(f"data_region {bank:02X} {s:04X} {e:04X}")
        total_regions += len(regions)

        # function bounds: next entry in bank, clamped to the containing code run
        starts = sorted(ents)
        run_ix = {r[0]: r for r in runs}
        sorted_runs = sorted(r[0] for r in runs)
        import bisect
        for i, pc in enumerate(starts):
            ea = (bank << 16) | pc
            ri = bisect.bisect_right(sorted_runs, ea) - 1
            run_end = None
            if ri >= 0:
                rstart = sorted_runs[ri]
                rlen = run_ix[rstart][1]
                if ea < rstart + rlen:
                    run_end = (rstart + rlen) & 0xFFFF
            nxt = starts[i + 1] if i + 1 < len(starts) else None
            end = min(x for x in (run_end, nxt, 0x10000) if x is not None)
            rec = ents[pc]
            lines.append(
                f"func {rec['name']} {pc:04X} end:{end & 0xFFFF or 0xFFFF:04X} "
                f"entry_mx:{rec['mx'][0]},{rec['mx'][1]}")
        total_funcs += len(starts)

        lines.extend(dispatch.get(bank, []))
        lines.extend(unresolved.get(bank, []))
        lines.append("")
        (out / f"bank{bank:02x}.cfg").write_text("\n".join(lines), newline="\n")

    print(f"banks: {len(banks)}  funcs: {total_funcs}  data_regions: {total_regions}  "
          f"dispatch sites: {n_sites} ({n_targets} targets)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
