/* dkc1_wram_gen.h — GENERATED by tools/gen_wram_header.py.
 * DO NOT EDIT. Regenerate after RAM-map/rename updates:
 *   python tools/gen_wram_header.py
 * Views over authentic WRAM (offset = address & 0x1FFFF);
 * little-endian, exact 16-bit wrap. Never duplicated state. */
#ifndef DKC1_WRAM_GEN_H
#define DKC1_WRAM_GEN_H

#include <stdint.h>

static inline uint8_t Dkc1WramU8(const uint8_t *wram,
                                 uint32_t off) {
  return wram[off];
}
static inline uint16_t Dkc1WramU16(const uint8_t *wram,
                                   uint32_t off) {
  return (uint16_t)(wram[off] | ((uint16_t)wram[off + 1] << 8));
}
static inline void Dkc1WramSetU8(uint8_t *wram, uint32_t off,
                                 uint8_t value) {
  wram[off] = value;
}
static inline void Dkc1WramSetU16(uint8_t *wram, uint32_t off,
                                  uint16_t value) {
  wram[off] = (uint8_t)value;
  wram[off + 1] = (uint8_t)(value >> 8);
}

/* actor SoA slot: the raw even byte index the game keeps in
 * X/Y ($02..$32); pass it through unchanged. */
#define DKC1_ACTOR_SLOT_FIRST 0x02u
#define DKC1_ACTOR_SLOT_LAST 0x32u
#define DKC1_ACTOR_SLOT_STEP 0x04u

/* --- named WRAM offsets (RAM map + curated overlay) --- */
#define DKC1_WRAM_Global_EntranceIDLo 0x003Eu  /* !RAM_DKC1_Global_EntranceIDLo */
#define DKC1_WRAM_CurrentSpriteSlot 0x0082u  /* !RAM_DKC1_NorSpr_CurrentIndexLo (curated: CurrentSpriteSlot) */
#define DKC1_WRAM_OAMWriteIndex 0x008Eu  /* !RAM_DKC1_Global_OAMIndexLo (curated: OAMWriteIndex) */
#define DKC1_WRAM_Global_OAMBuffer 0x0200u  /* !RAM_DKC1_Global_OAMBuffer */
#define DKC1_WRAM_JoypadHeld 0x0500u  /* !RAM_DKC1_Global_HeldButtonsLoP1 (curated: JoypadHeld) */
#define DKC1_WRAM_Global_HeldButtonsLoP2 0x0502u  /* !RAM_DKC1_Global_HeldButtonsLoP2 */
#define DKC1_WRAM_JoypadPressed 0x0504u  /* !RAM_DKC1_Global_PressedButtonsLoP1 (curated: JoypadPressed) */
#define DKC1_WRAM_Global_PressedButtonsLoP2 0x0506u  /* !RAM_DKC1_Global_PressedButtonsLoP2 */
#define DKC1_WRAM_Global_HeldButtonsLo 0x050Eu  /* !RAM_DKC1_Global_HeldButtonsLo */
#define DKC1_WRAM_Global_PressedButtonsLo 0x0510u  /* !RAM_DKC1_Global_PressedButtonsLo */
#define DKC1_WRAM_Global_ScreenDisplayRegister 0x051Au  /* !RAM_DKC1_Global_ScreenDisplayRegister */
#define DKC1_WRAM_HUD_BananaDisplayCount 0x0529u  /* !RAM_DKC1_Player_DisplayedBananaCountLo (curated: HUD_BananaDisplayCount) */
#define DKC1_WRAM_HUD_BananaDigits 0x052Bu  /* !RAM_DKC1_Player_BananaCountOnesDigit (curated: HUD_BananaDigits) */
#define DKC1_WRAM_Player_BananaCountTensDigit 0x052Cu  /* !RAM_DKC1_Player_BananaCountTensDigit */
#define DKC1_WRAM_Player_BananaCountHundredsDigit 0x052Du  /* !RAM_DKC1_Player_BananaCountHundredsDigit */
#define DKC1_WRAM_HUD_CounterShowTimer 0x052Fu  /* !RAM_DKC1_Level_ShowBananaCountTimerLo (curated: HUD_CounterShowTimer) */
#define DKC1_WRAM_Level_FreeMovementDebugFlagLo 0x0535u  /* !RAM_DKC1_Level_FreeMovementDebugFlagLo */
#define DKC1_WRAM_Level_GiveBackAnimalBuddyFlagLo 0x055Du  /* !RAM_DKC1_Level_GiveBackAnimalBuddyFlagLo */
#define DKC1_WRAM_Global_CurrentLanguageLo 0x0567u  /* !RAM_DKC1_Global_CurrentLanguageLo */
#define DKC1_WRAM_Global_CheatCodeFlagsLo 0x056Bu  /* !RAM_DKC1_Global_CheatCodeFlagsLo */
#define DKC1_WRAM_FileSelect_WaitToFadeBackToIntroTimerLo 0x056Du  /* !RAM_DKC1_FileSelect_WaitToFadeBackToIntroTimerLo */
#define DKC1_WRAM_Player_CurrentKongLo 0x056Fu  /* !RAM_DKC1_Player_CurrentKongLo */
#define DKC1_WRAM_Player_WinkyTokenCount 0x0571u  /* !RAM_DKC1_Player_WinkyTokenCount */
#define DKC1_WRAM_Player_CurrentLifeCountLo 0x0575u  /* !RAM_DKC1_Player_CurrentLifeCountLo */
#define DKC1_WRAM_Player_DisplayedLifeCountLo 0x0577u  /* !RAM_DKC1_Player_DisplayedLifeCountLo */
#define DKC1_WRAM_BananaCount 0x057Bu  /* !RAM_DKC1_Player_CurrentBananaCountLo (curated: BananaCount) */
#define DKC1_WRAM_Player_CollectedKONGLettersLo 0x057Fu  /* !RAM_DKC1_Player_CollectedKONGLettersLo */
#define DKC1_WRAM_FileSelect_CurrentSelectionLo 0x0581u  /* !RAM_DKC1_FileSelect_CurrentSelectionLo */
#define DKC1_WRAM_CameraX 0x088Bu  /* !RAM_DKC1_Global_Layer1XPosLo (curated: CameraX) */
#define DKC1_WRAM_CameraY 0x0895u  /* !RAM_DKC1_Global_Layer1YPosLo (curated: CameraY) */
#define DKC1_WRAM_NorSpr_CurrentOAMZPosLo 0x0A7Du  /* !RAM_DKC1_NorSpr_CurrentOAMZPosLo */
#define DKC1_WRAM_NorSpr_DrawOrderIndexLo 0x0AB1u  /* !RAM_DKC1_NorSpr_DrawOrderIndexLo */
#define DKC1_WRAM_NorSpr_DisplayedPoseLo 0x0AE5u  /* !RAM_DKC1_NorSpr_DisplayedPoseLo */
#define DKC1_WRAM_SprXPos 0x0B19u  /* !RAM_DKC1_NorSpr_XPosLo (curated: SprXPos) */
#define DKC1_WRAM_NorSpr_OAMZPosLo 0x0B8Du  /* !RAM_DKC1_NorSpr_OAMZPosLo */
#define DKC1_WRAM_SprYPos 0x0BC1u  /* !RAM_DKC1_NorSpr_YPosLo (curated: SprYPos) */
#define DKC1_WRAM_SprSurfaceY 0x0C35u  /* !RAM_DKC1_NorSpr_RAMTable0C35Lo (curated: SprSurfaceY) */
#define DKC1_WRAM_SprFlags 0x0C69u  /* !RAM_DKC1_NorSpr_YXPPCCCTLo (curated: SprFlags) */
#define DKC1_WRAM_NorSpr_RAMTable0CDDLo 0x0CDDu  /* !RAM_DKC1_NorSpr_RAMTable0CDDLo */
#define DKC1_WRAM_SprAnimFrame 0x0D11u  /* !RAM_DKC1_NorSpr_CurrentPoseLo (curated: SprAnimFrame) */
#define DKC1_WRAM_NorSpr_SpriteIDLo 0x0D45u  /* !RAM_DKC1_NorSpr_SpriteIDLo */
#define DKC1_WRAM_SprXSubpixel 0x0DB9u  /* !RAM_DKC1_NorSpr_RAMTable0DB9Lo (curated: SprXSubpixel) */
#define DKC1_WRAM_NorSpr_RAMTable0DEDLo 0x0DEDu  /* !RAM_DKC1_NorSpr_RAMTable0DEDLo */
#define DKC1_WRAM_SprYSubpixel 0x0E21u  /* !RAM_DKC1_NorSpr_RAMTable0E21Lo (curated: SprYSubpixel) */
#define DKC1_WRAM_NorSpr_RAMTable0E55Lo 0x0E55u  /* !RAM_DKC1_NorSpr_RAMTable0E55Lo */
#define DKC1_WRAM_SprXVelocity 0x0E89u  /* !RAM_DKC1_NorSpr_XSpeedLo (curated: SprXVelocity) */
#define DKC1_WRAM_NorSpr_RAMTable0EBDLo 0x0EBDu  /* !RAM_DKC1_NorSpr_RAMTable0EBDLo */
#define DKC1_WRAM_SprYVelocity 0x0EF1u  /* !RAM_DKC1_NorSpr_YSpeedLo (curated: SprYVelocity) */
#define DKC1_WRAM_NorSpr_RAMTable0F25Lo 0x0F25u  /* !RAM_DKC1_NorSpr_RAMTable0F25Lo */
#define DKC1_WRAM_NorSpr_RAMTable0F59Lo 0x0F59u  /* !RAM_DKC1_NorSpr_RAMTable0F59Lo */
#define DKC1_WRAM_NorSpr_RAMTable0F8DLo 0x0F8Du  /* !RAM_DKC1_NorSpr_RAMTable0F8DLo */
#define DKC1_WRAM_NorSpr_RAMTable0FC1Lo 0x0FC1u  /* !RAM_DKC1_NorSpr_RAMTable0FC1Lo */
#define DKC1_WRAM_NorSpr_RAMTable0FF5Lo 0x0FF5u  /* !RAM_DKC1_NorSpr_RAMTable0FF5Lo */
#define DKC1_WRAM_NorSpr_RAMTable1029Lo 0x1029u  /* !RAM_DKC1_NorSpr_RAMTable1029Lo */
#define DKC1_WRAM_NorSpr_RAMTable109DLo 0x109Du  /* !RAM_DKC1_NorSpr_RAMTable109DLo */
#define DKC1_WRAM_SprAnimID 0x10D1u  /* !RAM_DKC1_NorSpr_AnimationIDLo (curated: SprAnimID) */
#define DKC1_WRAM_SprAnimTimer 0x1105u  /* !RAM_DKC1_NorSpr_DisplayCurrentPoseTimerLo (curated: SprAnimTimer) */
#define DKC1_WRAM_SprAnimSpeed 0x1139u  /* !RAM_DKC1_NorSpr_AnimationSpeedLo (curated: SprAnimSpeed) */
#define DKC1_WRAM_SprAnimScriptPtr 0x116Du  /* !RAM_DKC1_NorSpr_AnimationScriptIndexLo (curated: SprAnimScriptPtr) */
#define DKC1_WRAM_NorSpr_RAMTable11A1Lo 0x11A1u  /* !RAM_DKC1_NorSpr_RAMTable11A1Lo */
#define DKC1_WRAM_NorSpr_RAMTable11D5Lo 0x11D5u  /* !RAM_DKC1_NorSpr_RAMTable11D5Lo */
#define DKC1_WRAM_SprSurfaceAttr 0x1209u  /* !RAM_DKC1_NorSpr_RAMTable1209Lo (curated: SprSurfaceAttr) */
#define DKC1_WRAM_NorSpr_RAMTable123DLo 0x123Du  /* !RAM_DKC1_NorSpr_RAMTable123DLo */
#define DKC1_WRAM_NorSpr_RAMTable1271Lo 0x1271u  /* !RAM_DKC1_NorSpr_RAMTable1271Lo */
#define DKC1_WRAM_SprCollisionFlags 0x12A5u  /* !RAM_DKC1_NorSpr_RAMTable12A5Lo (curated: SprCollisionFlags) */
#define DKC1_WRAM_NorSpr_RAMTable12D9Lo 0x12D9u  /* !RAM_DKC1_NorSpr_RAMTable12D9Lo */
#define DKC1_WRAM_SprAnimCallbackBank 0x130Du  /* !RAM_DKC1_NorSpr_RAMTable130DLo (curated: SprAnimCallbackBank) */
#define DKC1_WRAM_SprAnimCallbackAddr 0x1341u  /* !RAM_DKC1_NorSpr_RAMTable1341Lo (curated: SprAnimCallbackAddr) */
#define DKC1_WRAM_NorSpr_RAMTable1375Lo 0x1375u  /* !RAM_DKC1_NorSpr_RAMTable1375Lo */
#define DKC1_WRAM_NorSpr_RAMTable13E9Lo 0x13E9u  /* !RAM_DKC1_NorSpr_RAMTable13E9Lo */
#define DKC1_WRAM_NorSpr_RAMTable145DLo 0x145Du  /* !RAM_DKC1_NorSpr_RAMTable145DLo */
#define DKC1_WRAM_NorSpr_RAMTable1491Lo 0x1491u  /* !RAM_DKC1_NorSpr_RAMTable1491Lo */
#define DKC1_WRAM_NorSpr_RAMTable14C5Lo 0x14C5u  /* !RAM_DKC1_NorSpr_RAMTable14C5Lo */
#define DKC1_WRAM_NorSpr_RAMTable14F9Lo 0x14F9u  /* !RAM_DKC1_NorSpr_RAMTable14F9Lo */
#define DKC1_WRAM_NorSpr_RAMTable152DLo 0x152Du  /* !RAM_DKC1_NorSpr_RAMTable152DLo */
#define DKC1_WRAM_NorSpr_RAMTable1561Lo 0x1561u  /* !RAM_DKC1_NorSpr_RAMTable1561Lo */
#define DKC1_WRAM_SprEventFlags 0x1595u  /* !RAM_DKC1_NorSpr_RAMTable1595Lo (curated: SprEventFlags) */
#define DKC1_WRAM_NorSpr_RAMTable15C9Lo 0x15C9u  /* !RAM_DKC1_NorSpr_RAMTable15C9Lo */
#define DKC1_WRAM_NorSpr_RAMTable15FDLo 0x15FDu  /* !RAM_DKC1_NorSpr_RAMTable15FDLo */
#define DKC1_WRAM_SprSurfaceDistance 0x1631u  /* !RAM_DKC1_NorSpr_RAMTable1631Lo (curated: SprSurfaceDistance) */
#define DKC1_WRAM_NorSpr_RAMTable1665Lo 0x1665u  /* !RAM_DKC1_NorSpr_RAMTable1665Lo */
#define DKC1_WRAM_NorSpr_GraphicsDMATable 0x170Fu  /* !RAM_DKC1_NorSpr_GraphicsDMATable */
#define DKC1_WRAM_Level_CameraYPosLo 0x1A4Cu  /* !RAM_DKC1_Level_CameraYPosLo */
#define DKC1_WRAM_Level_CameraXPosLo 0x1A62u  /* !RAM_DKC1_Level_CameraXPosLo */
#define DKC1_WRAM_Global_SpritePaletteUploadTable 0x1A8Fu  /* !RAM_DKC1_Global_SpritePaletteUploadTable */
#define DKC1_WRAM_Global_CurrentlyLoadedSpritePalettePtrsLo 0x1AD3u  /* !RAM_DKC1_Global_CurrentlyLoadedSpritePalettePtrsLo */
#define DKC1_WRAM_Global_DecompressionBuffer 0x79FCu  /* !RAM_DKC1_Global_DecompressionBuffer */
#define DKC1_WRAM_Level_SpritePaletteBuffer 0x12779u  /* !RAM_DKC1_Level_SpritePaletteBuffer */

/* --- actor SoA per-field accessors --- */
static inline uint16_t Dkc1Actor_CurrentSpriteSlot(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0082u + slot);
}
static inline void Dkc1Actor_SetCurrentSpriteSlot(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0082u + slot, value);
}
static inline uint16_t Dkc1Actor_CurrentOAMZPosLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0A7Du + slot);
}
static inline void Dkc1Actor_SetCurrentOAMZPosLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0A7Du + slot, value);
}
static inline uint16_t Dkc1Actor_DrawOrderIndexLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0AB1u + slot);
}
static inline void Dkc1Actor_SetDrawOrderIndexLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0AB1u + slot, value);
}
static inline uint16_t Dkc1Actor_DisplayedPoseLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0AE5u + slot);
}
static inline void Dkc1Actor_SetDisplayedPoseLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0AE5u + slot, value);
}
static inline uint16_t Dkc1Actor_SprXPos(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0B19u + slot);
}
static inline void Dkc1Actor_SetSprXPos(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0B19u + slot, value);
}
static inline uint16_t Dkc1Actor_OAMZPosLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0B8Du + slot);
}
static inline void Dkc1Actor_SetOAMZPosLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0B8Du + slot, value);
}
static inline uint16_t Dkc1Actor_SprYPos(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0BC1u + slot);
}
static inline void Dkc1Actor_SetSprYPos(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0BC1u + slot, value);
}
static inline uint16_t Dkc1Actor_SprSurfaceY(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0C35u + slot);
}
static inline void Dkc1Actor_SetSprSurfaceY(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0C35u + slot, value);
}
static inline uint16_t Dkc1Actor_SprFlags(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0C69u + slot);
}
static inline void Dkc1Actor_SetSprFlags(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0C69u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable0CDDLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0CDDu + slot);
}
static inline void Dkc1Actor_SetRAMTable0CDDLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0CDDu + slot, value);
}
static inline uint16_t Dkc1Actor_SprAnimFrame(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0D11u + slot);
}
static inline void Dkc1Actor_SetSprAnimFrame(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0D11u + slot, value);
}
static inline uint16_t Dkc1Actor_SpriteIDLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0D45u + slot);
}
static inline void Dkc1Actor_SetSpriteIDLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0D45u + slot, value);
}
static inline uint16_t Dkc1Actor_SprXSubpixel(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0DB9u + slot);
}
static inline void Dkc1Actor_SetSprXSubpixel(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0DB9u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable0DEDLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0DEDu + slot);
}
static inline void Dkc1Actor_SetRAMTable0DEDLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0DEDu + slot, value);
}
static inline uint16_t Dkc1Actor_SprYSubpixel(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0E21u + slot);
}
static inline void Dkc1Actor_SetSprYSubpixel(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0E21u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable0E55Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0E55u + slot);
}
static inline void Dkc1Actor_SetRAMTable0E55Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0E55u + slot, value);
}
static inline uint16_t Dkc1Actor_SprXVelocity(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0E89u + slot);
}
static inline void Dkc1Actor_SetSprXVelocity(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0E89u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable0EBDLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0EBDu + slot);
}
static inline void Dkc1Actor_SetRAMTable0EBDLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0EBDu + slot, value);
}
static inline uint16_t Dkc1Actor_SprYVelocity(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0EF1u + slot);
}
static inline void Dkc1Actor_SetSprYVelocity(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0EF1u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable0F25Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0F25u + slot);
}
static inline void Dkc1Actor_SetRAMTable0F25Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0F25u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable0F59Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0F59u + slot);
}
static inline void Dkc1Actor_SetRAMTable0F59Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0F59u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable0F8DLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0F8Du + slot);
}
static inline void Dkc1Actor_SetRAMTable0F8DLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0F8Du + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable0FC1Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0FC1u + slot);
}
static inline void Dkc1Actor_SetRAMTable0FC1Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0FC1u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable0FF5Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x0FF5u + slot);
}
static inline void Dkc1Actor_SetRAMTable0FF5Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x0FF5u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable1029Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1029u + slot);
}
static inline void Dkc1Actor_SetRAMTable1029Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1029u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable109DLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x109Du + slot);
}
static inline void Dkc1Actor_SetRAMTable109DLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x109Du + slot, value);
}
static inline uint16_t Dkc1Actor_SprAnimID(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x10D1u + slot);
}
static inline void Dkc1Actor_SetSprAnimID(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x10D1u + slot, value);
}
static inline uint16_t Dkc1Actor_SprAnimTimer(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1105u + slot);
}
static inline void Dkc1Actor_SetSprAnimTimer(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1105u + slot, value);
}
static inline uint16_t Dkc1Actor_SprAnimSpeed(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1139u + slot);
}
static inline void Dkc1Actor_SetSprAnimSpeed(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1139u + slot, value);
}
static inline uint16_t Dkc1Actor_SprAnimScriptPtr(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x116Du + slot);
}
static inline void Dkc1Actor_SetSprAnimScriptPtr(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x116Du + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable11A1Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x11A1u + slot);
}
static inline void Dkc1Actor_SetRAMTable11A1Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x11A1u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable11D5Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x11D5u + slot);
}
static inline void Dkc1Actor_SetRAMTable11D5Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x11D5u + slot, value);
}
static inline uint16_t Dkc1Actor_SprSurfaceAttr(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1209u + slot);
}
static inline void Dkc1Actor_SetSprSurfaceAttr(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1209u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable123DLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x123Du + slot);
}
static inline void Dkc1Actor_SetRAMTable123DLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x123Du + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable1271Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1271u + slot);
}
static inline void Dkc1Actor_SetRAMTable1271Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1271u + slot, value);
}
static inline uint16_t Dkc1Actor_SprCollisionFlags(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x12A5u + slot);
}
static inline void Dkc1Actor_SetSprCollisionFlags(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x12A5u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable12D9Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x12D9u + slot);
}
static inline void Dkc1Actor_SetRAMTable12D9Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x12D9u + slot, value);
}
static inline uint16_t Dkc1Actor_SprAnimCallbackBank(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x130Du + slot);
}
static inline void Dkc1Actor_SetSprAnimCallbackBank(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x130Du + slot, value);
}
static inline uint16_t Dkc1Actor_SprAnimCallbackAddr(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1341u + slot);
}
static inline void Dkc1Actor_SetSprAnimCallbackAddr(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1341u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable1375Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1375u + slot);
}
static inline void Dkc1Actor_SetRAMTable1375Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1375u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable13E9Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x13E9u + slot);
}
static inline void Dkc1Actor_SetRAMTable13E9Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x13E9u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable145DLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x145Du + slot);
}
static inline void Dkc1Actor_SetRAMTable145DLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x145Du + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable1491Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1491u + slot);
}
static inline void Dkc1Actor_SetRAMTable1491Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1491u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable14C5Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x14C5u + slot);
}
static inline void Dkc1Actor_SetRAMTable14C5Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x14C5u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable14F9Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x14F9u + slot);
}
static inline void Dkc1Actor_SetRAMTable14F9Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x14F9u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable152DLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x152Du + slot);
}
static inline void Dkc1Actor_SetRAMTable152DLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x152Du + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable1561Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1561u + slot);
}
static inline void Dkc1Actor_SetRAMTable1561Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1561u + slot, value);
}
static inline uint16_t Dkc1Actor_SprEventFlags(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1595u + slot);
}
static inline void Dkc1Actor_SetSprEventFlags(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1595u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable15C9Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x15C9u + slot);
}
static inline void Dkc1Actor_SetRAMTable15C9Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x15C9u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable15FDLo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x15FDu + slot);
}
static inline void Dkc1Actor_SetRAMTable15FDLo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x15FDu + slot, value);
}
static inline uint16_t Dkc1Actor_SprSurfaceDistance(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1631u + slot);
}
static inline void Dkc1Actor_SetSprSurfaceDistance(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1631u + slot, value);
}
static inline uint16_t Dkc1Actor_RAMTable1665Lo(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x1665u + slot);
}
static inline void Dkc1Actor_SetRAMTable1665Lo(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x1665u + slot, value);
}
static inline uint16_t Dkc1Actor_GraphicsDMATable(const uint8_t *wram, uint32_t slot) {
  return Dkc1WramU16(wram, 0x170Fu + slot);
}
static inline void Dkc1Actor_SetGraphicsDMATable(uint8_t *wram, uint32_t slot, uint16_t value) {
  Dkc1WramSetU16(wram, 0x170Fu + slot, value);
}

/* --- struct mirrors (Asar struct declarations) --- */
#define DKC1_Global_OAMBuffer_BASE 0x0200u
#define DKC1_Global_OAMBuffer_STRIDE 0x04u
static inline uint8_t Dkc1_Global_OAMBuffer_XDisp(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x0200u + index * 0x04u + 0x00u);
}
static inline uint8_t Dkc1_Global_OAMBuffer_YDisp(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x0200u + index * 0x04u + 0x01u);
}
static inline uint8_t Dkc1_Global_OAMBuffer_Tile(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x0200u + index * 0x04u + 0x02u);
}
static inline uint8_t Dkc1_Global_OAMBuffer_Prop(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x0200u + index * 0x04u + 0x03u);
}
#define DKC1_Global_UpperOAMBuffer_BASE 0x0400u
#define DKC1_Global_UpperOAMBuffer_STRIDE 0x01u
static inline uint8_t Dkc1_Global_UpperOAMBuffer_Slot(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x0400u + index * 0x01u + 0x00u);
}
#define DKC1_NorSpr_GraphicsDMATable_BASE 0x170Fu
#define DKC1_NorSpr_GraphicsDMATable_STRIDE 0x08u
static inline uint8_t Dkc1_NorSpr_GraphicsDMATable_SizeLo(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x170Fu + index * 0x08u + 0x00u);
}
static inline uint8_t Dkc1_NorSpr_GraphicsDMATable_SizeHi(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x170Fu + index * 0x08u + 0x01u);
}
static inline uint8_t Dkc1_NorSpr_GraphicsDMATable_VRAMAddressLo(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x170Fu + index * 0x08u + 0x02u);
}
static inline uint8_t Dkc1_NorSpr_GraphicsDMATable_VRAMAddressHi(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x170Fu + index * 0x08u + 0x03u);
}
static inline uint8_t Dkc1_NorSpr_GraphicsDMATable_SourceLo(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x170Fu + index * 0x08u + 0x04u);
}
static inline uint8_t Dkc1_NorSpr_GraphicsDMATable_SourceHi(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x170Fu + index * 0x08u + 0x05u);
}
static inline uint8_t Dkc1_NorSpr_GraphicsDMATable_SourceBank(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x170Fu + index * 0x08u + 0x06u);
}
static inline uint8_t Dkc1_NorSpr_GraphicsDMATable_Unused(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x170Fu + index * 0x08u + 0x07u);
}
#define DKC1_NorSpr_SpritePaletteUploadTable_BASE 0x1A8Fu
#define DKC1_NorSpr_SpritePaletteUploadTable_STRIDE 0x04u
static inline uint8_t Dkc1_NorSpr_SpritePaletteUploadTable_PtrLo(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x1A8Fu + index * 0x04u + 0x00u);
}
static inline uint8_t Dkc1_NorSpr_SpritePaletteUploadTable_PtrHi(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x1A8Fu + index * 0x04u + 0x01u);
}
static inline uint8_t Dkc1_NorSpr_SpritePaletteUploadTable_PtrBank(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x1A8Fu + index * 0x04u + 0x02u);
}
static inline uint8_t Dkc1_NorSpr_SpritePaletteUploadTable_Index(const uint8_t *wram, uint32_t index) {
  return Dkc1WramU8(wram, 0x1A8Fu + index * 0x04u + 0x03u);
}

#endif /* DKC1_WRAM_GEN_H */
